# Generated by Django 4.2.6 on 2024-08-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('image', models.ImageField(upload_to='image')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
            ],
        ),
    ]
