# Generated by Django 4.2.6 on 2024-08-20 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0003_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seller_id',
            field=models.ForeignKey(db_column='seller_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
